import OpenAI from 'openai';


const openai = new OpenAI({
    apiKey: '', // Replace with your OpenAI API key
    dangerouslyAllowBrowser: true
});

const submitButton = document.getElementById('submit-button') as HTMLButtonElement;
const captchaInput = document.getElementById('captcha-input') as HTMLTextAreaElement;
const responseContainer = document.getElementById('response-container') as HTMLDivElement;

if (submitButton && captchaInput && responseContainer) {
    console.log('Elements found:', { submitButton, captchaInput, responseContainer });

    submitButton.addEventListener('click', async () => {
        console.log('Submitting captcha...');
        const userText = captchaInput.value.trim();
        if (!userText) {
            responseContainer.innerHTML = "Please enter some text.";
            return;
        }

        try {
            const response = await openai.chat.completions.create({
                model: 'gpt-4o',
                messages: [
                    { role: 'system', content: 'You are an AI CAPTCHA verifier. Analyze the given text and determine with precision if it was likely generated by a human or an AI. Assess creativity, natural language flow, and depth of intent. Be highly critical, focusing on subtleties like emotion, nuance, and authenticity. Carefully scrutinize whether the thought process reflects human-like reasoning or algorithmic patterns. Your evaluation must be concise, focused, and no longer than 100 words.' },
                    { role: 'user', content: userText }
                ],
                max_tokens: 100,
            });

            responseContainer.innerHTML = response.choices?.[0]?.message?.content?.trim() || "No response from AI.";
            responseContainer.classList.add('filled');
        } catch (error) {
            console.error('Error with OpenAI API:', error);
            responseContainer.innerHTML = "Something went wrong, please try again later.";
        }
    });


    captchaInput.addEventListener('input', () => autoExpand(captchaInput));
} else {
    console.error('Required elements not found in the DOM.');
}


function autoExpand(textarea: HTMLTextAreaElement) {
    textarea.style.height = 'auto';
    textarea.style.height = textarea.scrollHeight + 'px';
}